services:
  service:
    command: uv run uvicorn open_telemetry_experiment_service.app:create_app --factory --host 0.0.0.0 --port 8000 --reload
    environment:
      SERVICE_ENV: dev
    volumes:
      - ./apps/service/src:/app/src

  worker-api:
    command: uv run uvicorn open_telemetry_experiment_worker.app:create_app --factory --host 0.0.0.0 --port 8000 --reload
    environment:
      WORKER_ENV: dev
      WORKER_REDIS_URL: redis://redis:6379
      WORKER_SERVICE_BASE_URL: http://service:8000/api/v1
    volumes:
      - ./apps/worker/src:/app/src

  worker-worker:
    command: uv run watchfiles "saq open_telemetry_experiment_worker.worker.settings" /app/src
    environment:
      WORKER_ENV: dev
      WORKER_REDIS_URL: redis://redis:6379
      WORKER_SERVICE_BASE_URL: http://service:8000/api/v1
    volumes:
      - ./apps/worker/src:/app/src

  web:
    build:
      context: ./apps/web
      target: dev
    command: sh -c "bunx drizzle-kit push && bun run dev"
    environment:
      WEB_ENV: dev
    volumes:
      - ./apps/web/src:/app/src
      - ./apps/web/next.config.ts:/app/next.config.ts
      - ./apps/web/drizzle.config.ts:/app/drizzle.config.ts
